[AppRewrite] Part 5: Loaders in the `telestion-services` module
wuespace/telestion-core pull request #505
Opened 2022-02-16 16:22 UTC by fussel178

**DO NOT PUSH OR MERGE!**

### Summary 

n/a

### Details 

n/a

### Additional information 

n/a

### Related links 

- Fixes # .

### CLA

- [ ] I have signed the individual contributor's license agreement **and sent** it to the board of the WüSpace e. V. organization.

2022-03-01 16:45 UTC, cb0s requested changes
I mostly need more java docs. Apart from that as already stated in the previous PRs of the stacked PR: VERY GOOOD! ✔️

2022-03-01 16:45 UTC, cb0s commented on modules/telestion-services/src/main/java/de/wuespace/telestion/services/loader/verticle/AbstractVerticleLoader.java
> +	 * Gets called, when the loader receive verticles configuration.
```suggestion
	 * Gets called, when the loader receives verticle configurations.
```

2022-03-01 16:45 UTC, cb0s commented on modules/telestion-services/src/main/java/de/wuespace/telestion/services/loader/verticle/AbstractVerticleLoader.java
> +	 * @return a future which resolves when all verticles are deployed
Add Link to Future, pls :)

(multiple times)

2022-03-01 16:45 UTC, cb0s commented on modules/telestion-services/src/main/java/de/wuespace/telestion/services/loader/verticle/VerticleConfiguration.java
> +public record VerticleConfiguration(
And please add a description about the different properties of this record :)

2022-03-01 16:45 UTC, cb0s commented on modules/telestion-services/src/main/java/de/wuespace/telestion/services/loader/verticle/VerticleLoaderConfiguration.java
> +public interface VerticleLoaderConfiguration extends LoaderConfiguration {
Please let nobody make the song "We don't need no Java-Docs... 🎸" about our repository :D

2022-03-05 15:39 UTC, fussel178 commented on modules/telestion-services/src/main/java/de/wuespace/telestion/services/loader/VerticleLoader.java
> +		onConfiguration(launcher.getMainConfiguration()).onComplete(startPromise);
Done in [`ff4e091` (#505)](https://github.com/wuespace/telestion-core/pull/505/commits/ff4e091c2df60481b114d87da6bc968a6a2027b5)

2022-12-15 23:37 UTC, fussel178 commented
I'll close this pull request due to inactivity and re-create one pull request with a simpler implementation.
In this new pull request the [RFC: $ (dollar sign) operators in Application Configuration](https://github.com/wuespace/telestion/discussions/347) will also be addressed.

2022-12-15 23:37 UTC, closed without merging